# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Bump version
      id: bump_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
        DRY_RUN: true
        
    - name: Update Version
      run: mvn versions:set -DnewVersion=${{ steps.bump_version.outputs.new_tag }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        TOKEN: ${{ secrets.TOKEN }}
        
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        TOKEN: ${{ secrets.TOKEN }}
      with:
        title: Release ${{ steps.bump_version.outputs.new_tag }}
        
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
