name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      tf_action_type:
        type: choice
        description: What to do?
        options: 
        - plan
        - apply


jobs:
  plan:
    if: (contains('refs/heads/dev', github.ref) && ${{ github.event.inputs.tf_action_type == 'plan' }})
    runs-on: ubuntu-latest

    steps:
    - name: Run Plan
      run: echo "${{ github.event.inputs.tf_action_type }}"
      
  apply:
    if: ${{ github.event.inputs.tf_action_type == 'apply' }}
    runs-on: ubuntu-latest

    steps:
    - name: Run Apply
      run: echo "${{ github.event.inputs.tf_action_type }}"
